version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.24-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/file_loader_and_processor/django_static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/file_loader_and_processor/Dockerfile
        entrypoint: /app/docker/file_loader_and_processor/server-entrypoint.sh
        volumes:
            - static_volume:/app/file_loader_and_processor/django_static
        expose:
            - 8000     
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: picaso_postgres
            POSTGRES_USER: picaso_postgres_user
            POSTGRES_PASSWORD: picaso_postgres_password
            POSTGRES_PORT: 5432
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/file_loader_and_processor/Dockerfile
        entrypoint: /app/docker/file_loader_and_processor/worker-entrypoint.sh
        volumes:
            - static_volume:/app/file_loader_and_processor/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: picaso_postgres
            POSTGRES_USER: picaso_postgres_user
            POSTGRES_PASSWORD: picaso_postgres_password
            POSTGRES_PORT: 5432
        depends_on:
            - server
            - redis
    redis:
        restart: unless-stopped
        image: redis:7.2-alpine 
        expose:
            - 6379
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: picaso_postgres
            POSTGRES_USER: picaso_postgres_user
            POSTGRES_PASSWORD: picaso_postgres_password
        expose:
            - 5432
    
volumes:
    static_volume: {}
    postgres_data: {}